непонятно
mar4ehk0/go pull request #10
Opened 2024-10-15 22:17 UTC by mar4ehk0

2024-10-16 19:17 UTC, vladislavmass requested changes

2024-10-16 19:17 UTC, vladislavmass commented on hw09_serialize/api/book/book.proto
> +message Book {
Должно быть еще сообщения для слайса книг

2024-10-18 07:36 UTC, mar4ehk0 commented on hw09_serialize/api/book/book.proto
> +message Book {
добавил

2024-10-18 07:37 UTC, mar4ehk0 commented on hw09_serialize/internal/book/books.go
> +	// data := []rune(string(value))
@vladislavmass есть ли смысл работать со строкой или просто использовать библиотеку как я сделал ниже?

2024-10-18 09:27 UTC, vladislavmass approved these changes

2024-10-18 09:29 UTC, vladislavmass commented on hw09_serialize/internal/book/books.go
> +	// data := []rune(string(value))
на самом деле тут даже не нужно было создавать новую структуру. Хватило бы создать просто метод который принимает слайс байт, а возвращет слайс книг. Внутри можно было просто вызвать json.Unmarshal

2024-10-18 09:38 UTC, merged