hw10_motion_sensor: реализовал ДЗ
mar4ehk0/go pull request #11
Opened 2024-10-21 20:37 UTC by mar4ehk0

## Домашнее задание №10 «Обработка данных сенсора движения»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~80 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-10-22 20:17 UTC, vladislavmass requested changes

2024-10-22 20:17 UTC, vladislavmass commented on hw10_motion_sensor/internal/calculator/calculator.go
> +			result := average(data)
Насовсем понимаю зачем тут массив, вариант с накопителем суммы и счетчиком был бы намного эффективнее

2024-10-22 20:17 UTC, vladislavmass commented on hw10_motion_sensor/go.mod
> +module github.com/mar4ehk0/hw10_motion_sensor
Неверное имя модуля

2024-10-22 20:17 UTC, vladislavmass commented on hw10_motion_sensor/cmd/main.go
> +			stopCh <- struct{}{}
Если хотите сделать такой механизм то лучше не отправлять сообщение, а просто закрыть канал

2024-10-22 20:17 UTC, vladislavmass commented on hw10_motion_sensor/cmd/main.go
> +			sensorCh <- data
Этот код может отработать более 1 минуты, хотя должен работать 1 минуту

2024-10-22 20:17 UTC, vladislavmass commented on hw10_motion_sensor/cmd/main.go
> +	sensorCh := make(chan int)
Каналы нужно закрывать

2024-10-27 15:11 UTC, mar4ehk0 commented on hw10_motion_sensor/internal/calculator/calculator.go
> +			result := average(data)
исправил

2024-10-27 15:11 UTC, mar4ehk0 commented on hw10_motion_sensor/go.mod
> +module github.com/mar4ehk0/hw10_motion_sensor
исправил

2024-10-27 15:11 UTC, mar4ehk0 commented on hw10_motion_sensor/cmd/main.go
> +			stopCh <- struct{}{}
переделал

2024-10-27 15:11 UTC, mar4ehk0 commented on hw10_motion_sensor/cmd/main.go
> +			sensorCh <- data
переделал

2024-10-27 15:11 UTC, mar4ehk0 commented on hw10_motion_sensor/cmd/main.go
> +	sensorCh := make(chan int)
закрываю теперь

2024-10-27 19:09 UTC, vladislavmass approved these changes

2024-10-27 19:09 UTC, vladislavmass commented on hw10_motion_sensor/internal/calculator/calculator.go
> +			averageCh <- float64(acm) / float64(limitItems)
Приведение типов тут можно убрать так как acm и так float64  и все выражение вернет float64

2024-10-27 19:57 UTC, merged