hw11_worker_pool: implemented
mar4ehk0/go pull request #12
Opened 2024-10-30 20:27 UTC by mar4ehk0

## Домашнее задание №11 «Пул воркеров»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~50 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-10-31 11:46 UTC, vladislavmass requested changes

2024-10-31 11:46 UTC, vladislavmass commented on hw11_worker_pool/internal/calculator/counter.go
> +	return strconv.Itoa(c.Value)
Данный метод структуры должен быть тоже потокобезопасен

2024-10-31 11:46 UTC, vladislavmass commented on hw11_worker_pool/cmd/main.go
> +	counter := calculator.Counter{Mutex: sync.Mutex{}}
Нет никакого смысла передавать новый мьютекс. Можно оставить `counter := calculator.Counter{}`

2024-10-31 21:21 UTC, mar4ehk0 commented on hw11_worker_pool/cmd/main.go
> +	counter := calculator.Counter{Mutex: sync.Mutex{}}
добавил RWMutex

2024-10-31 21:21 UTC, mar4ehk0 commented on hw11_worker_pool/internal/calculator/counter.go
> +	return strconv.Itoa(c.Value)
удалил

2024-11-01 05:50 UTC, vladislavmass approved these changes

2024-11-01 06:33 UTC, merged