HW02 is completed
mar4ehk0/go pull request #2
Opened 2024-08-20 16:30 UTC by mar4ehk0

fixed all issues

2024-08-21 05:16 UTC, vladislavmass requested changes

2024-08-21 05:16 UTC, vladislavmass commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Неверное имя модуля. Фраза `fixme_my_friend` тут не просто так

2024-08-21 05:16 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Если мы не смогли открыть файл, то мы не сможем его прочитать. Поэтому нам необходимо прервать выполнение функции и вернуть вызывающему коду ошибку. Для этого можно использовать следующую конструкцию `return nil,err`

2024-08-21 05:16 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Если мы вернем nil,nil. То вызывающий код не будет знать что у нас произошла ошибка. Поэтому в данном случае необходимо также вернуть ошибку `return nil,err`

2024-08-21 05:16 UTC, vladislavmass commented on hw02_fix_app/main.go
>  	printer.PrintStaff(staff)
В идеале было добавить эту строчку в блок else к if в 25 строке. Тоесть если файл считался без ошибок, то мы выводим считаные данные

2024-08-21 21:01 UTC, mar4ehk0 commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
fixed

2024-08-21 21:01 UTC, mar4ehk0 commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
fixed

2024-08-21 21:01 UTC, mar4ehk0 commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
fixed

2024-08-21 21:02 UTC, mar4ehk0 commented on hw02_fix_app/main.go
>  	printer.PrintStaff(staff)
fixed

2024-08-22 05:55 UTC, vladislavmass approved these changes

2024-08-22 07:54 UTC, merged