hw04_struct_comparator: implemented comparator
mar4ehk0/go pull request #4
Opened 2024-09-04 21:12 UTC by mar4ehk0

2024-09-04 21:15 UTC, mar4ehk0 commented on hw04_struct_comparator/cmd/main.go
> +	exampleComparatorRate(book1, book2)
понимаю что можно сделать проще, через цикл, но так как еще не было лекции  с мапами. то не стал мудрить. сделал более объемнее

2024-09-04 21:16 UTC, mar4ehk0 commented on hw04_struct_comparator/internal/book/book.go
> +	Rate   float32
В задании указано именно с большой буквы, тогда не понятен зачем тут гетеры/сеттеры? или переделать на приватную область видимости?

2024-09-05 03:23 UTC, vladislavmass requested changes

2024-09-05 03:23 UTC, vladislavmass commented on hw04_struct_comparator/internal/book/book.go
> +func (b Book) GetAuthor() string {
В го не принято у одной структуры использовать и Value и Pointer ресиверы. Все методы должны использовать либо value ресивер, либо Pointer. Но так как у нас есть методы меняющие поля структуры то использовать мы можем только Pointer ресивер

2024-09-05 03:23 UTC, vladislavmass commented on hw04_struct_comparator/internal/comparator/comparator.go
> +func (c Comparator) Compare(a book.Book, b book.Book) (bool, error) {
По условию задания этот метод не должен возвращать ошибку

2024-09-05 03:23 UTC, vladislavmass commented on hw04_struct_comparator/cmd/main.go
> +	exampleComparatorRate(book1, book2)
А в чем тут надобность мапы? Мапа нужна когда мы хотим по ключу получать значение. Если хотелось сделать это через цикл то тут лучше было бы использовать слайс. Хотя практической надобности ни в том, ни в другом нет

2024-09-05 15:43 UTC, mar4ehk0 commented on hw04_struct_comparator/cmd/main.go
> +	exampleComparatorRate(book1, book2)
исправил, через слайсы

2024-09-05 15:44 UTC, vladislavmass commented on hw04_struct_comparator/internal/book/book.go
> +	Rate   float32
`Реализуйте структуру Book со следующими неэкспортируемыми полями.` На основание этого текста можно сказать что поля должны быть с маленькой буквы

2024-09-05 15:44 UTC, mar4ehk0 commented on hw04_struct_comparator/internal/comparator/comparator.go
> +func (c Comparator) Compare(a book.Book, b book.Book) (bool, error) {
удалил error

2024-09-05 15:45 UTC, mar4ehk0 commented on hw04_struct_comparator/internal/book/book.go
> +func (b Book) GetAuthor() string {
ok, принял. исправил

2024-09-05 15:45 UTC, hungry-honeybadger commented on hw04_struct_comparator/internal/book/book.go
> +func (b Book) GetID() uint {
В go не принято называть геттеры со слова Get. В go принято называть гетеры именем поля с большой буквы

2024-09-06 12:34 UTC, mar4ehk0 commented on hw04_struct_comparator/internal/book/book.go
> +func (b Book) GetID() uint {
исправил

2024-09-06 13:11 UTC, vladislavmass approved these changes

2024-09-06 13:11 UTC, vladislavmass commented on hw04_struct_comparator/internal/book/book.go
> +func CreateBook(id uint, title string, author string, year uint, size uint, rate float32) Book {
Лучше все таки возвращать указатель на структуру, а не саму структуру

2024-09-06 13:15 UTC, mar4ehk0 commented on hw04_struct_comparator/internal/book/book.go
> +func CreateBook(id uint, title string, author string, year uint, size uint, rate float32) Book {
спасибо, учту

2024-09-28 11:06 UTC, merged