Hw07 word counter
mar4ehk0/go pull request #7
Opened 2024-10-06 21:11 UTC by mar4ehk0

## Домашнее задание №7 «Подсчет слов в тексте»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - main.go ~40 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 4 баллов

2024-10-07 04:03 UTC, vladislavmass requested changes

2024-10-07 04:03 UTC, vladislavmass commented on hw07_word_counter/internal/counter/counter.go
> +		if ok {
Данная конструкция тут лишняя. Лучше использовать просто `words[word]++`

2024-10-07 04:03 UTC, vladislavmass commented on hw07_word_counter/internal/counter/counter.go
> +	set := ",.!?"
Это строка никогда не меняется поэтому ее лучше сделать константой уровня пакета

2024-10-07 04:03 UTC, vladislavmass commented on hw07_word_counter/internal/counter/counter.go
> +		word := strings.Trim(v, set)
Из за этой строчки работа застряла где то посередине. Либо избавляться от нее, оставив все знаки препинания на месте, либо расширять список знаков препинания

2024-10-07 06:46 UTC, mar4ehk0 commented on hw07_word_counter/internal/counter/counter.go
> +		word := strings.Trim(v, set)
>Из за этой строчки работа застряла где то посередине
@vladislavmass можно подробнее, не могу понять. и что за работа?

2024-10-07 06:48 UTC, mar4ehk0 commented on hw07_word_counter/internal/counter/counter.go
> +		if ok {
исправил

2024-10-07 07:11 UTC, vladislavmass commented on hw07_word_counter/internal/counter/counter.go
> +		word := strings.Trim(v, set)
Тут ситуация такая что я ее принять не могу. Так как она вроде удаляет знаки препинания а вроде и нет.  То есть если мы дадим на вход строку.  `Он сказал: "Дима, Петя! Идем за мной"` В данном случае мы удалим запятую и восклицательный знак, а двоеточие и кавычки останутся. Варианта тут 2, как я написал выше либо оставлять все знаки препинания, либо удалять но тоже все

2024-10-08 13:35 UTC, mar4ehk0 commented on hw07_word_counter/internal/counter/counter.go
> +		word := strings.Trim(v, set)
исправил

2024-10-08 13:40 UTC, vladislavmass approved these changes

2024-10-08 15:31 UTC, merged